### ISSUE TITLE
Problem 5

### ISSUE THREAD

**Issue by ShubhangiSanyal** [ShubhangiSanyal/PBSR#1]
I have written the initial codes in `Q5_SSanyal.R` required for solving the 5th problem. Please go through them and let me know if any changes are to be made.

**Comment by ShubhangiSanyal** [comment]
While calculating the residual standard error, if I use n-1 as the degrees of freedom in the method of moments estimator, I'm getting the exact same value as in the `lm` model. But, in theory, I think we're supposed to use n-2 as the degrees of freedom which is giving slightly different results. Let me know which step should I follow.

**Comment by Sam-adhi2000** [comment]
> While calculating the residual standard error, if I use n-1 as the degrees of freedom in the method of moments estimator, I'm getting the exact same value as in the `lm` model. But, in theory, I think we're supposed to use n-2 as the degrees of freedom which is giving slightly different results. Let me know which step should I follow.

I think you should use n-2 degrees of freedom for the residual standard error as df= total number of obs-number of parameters to be estimated and here you have to estimate 2 parameters, so use n-2

**Comment by ShubhangiSanyal** [comment]
> > While calculating the residual standard error, if I use n-1 as the degrees of freedom in the method of moments estimator, I'm getting the exact same value as in the `lm` model. But, in theory, I think we're supposed to use n-2 as the degrees of freedom which is giving slightly different results. Let me know which step should I follow.
>
> I think you should use n-2 degrees of freedom for the residual standard error as df= total number of obs-number of parameters to be estimated and here you have to estimate 2 parameter, so use n-2

Sure, I will make the changes accordingly and edit the uploaded file.
