### ISSUE TITLE
Problem 1

### ISSUE THREAD

**Issue by ShubhangiSanyal** [ShubhangiSanyal/PBSR#10]
I have uploaded the solution to problem 1 in the `Report` folder of `Assignment_2`. Core statistical knowledge was applied following what was done in the class.

**Comment by Sam-adhi2000** [comment]
Checked markdown file from pull request and everything seems alright.

**Comment by subhashree303** [comment]
In part 6  of problem 1 u may write a bit more why poisson model was selected.

**Comment by ShubhangiSanyal** [comment]
Okay. I have added an explanation accordingly.
