### ISSUE TITLE
Problem 2

### ISSUE THREAD

**Issue by subhashree303** [ShubhangiSanyal/PBSR#3]
I have written the initial code for question no. 2 in file `Q2_SSaha`. Let me know if there are any changes to be made in it.

**Comment by ShubhangiSanyal** [comment]
> I have written the initial code for question no. 2 in file `Q2_SSaha`. Let me know if there are any changes to be made in it.

Refer to the following points:
1. Please change the function name to a more suitable one. 
2. I think you should also label the axes in all the histograms. Rest everything seems to be fine. I was able to reproduce all the results.

**Comment by subhashree303** [comment]
> > I have written the initial code for question no. 2 in file `Q2_SSaha`. Let me know if there are any changes to be made in it.
> 
> Refer to the following points:
> 
> 1. Please change the function name to a more suitable one.
> 2. I think you should also label the axes in all the histograms. Rest everything seems to be fine. I was able to reproduce all the results.

Sure,I will make the necessary changes.
