### ISSUE TITLE
Problem 3 review

### ISSUE THREAD

**Issue by Sam-adhi2000** [ShubhangiSanyal/PBSR#6]
I reviewed the code and feel that for subpart 1, instead of taking the initial values for the parameters of the model, you can do the following:
Suppose your dataset is named `a`, then take `p` as y=`length(a[a<65])/length(a)`  and the scale parameter as the `mean(a[a<65])/var(a[a<65])` and the shape parameter of `mean(a[a<65])/y` and same in case of `a>=65`
Follow these for subpart 2 as well
@subhashree303

**Comment by subhashree303** [comment]
Sure will make the following changes.
